### ISSUE TITLE
/pubnubsubhandler.py", line 124 : self_pubnubs is undefined. 

### ISSUE THREAD

**Issue by joelmoses** [w1ll1am23/pywinksub#2]
Perhaps "self._pubnubs"? :)

2019-06-11 10:04:17 INFO (Thread-3) [pubnubsubhandler] PubNub subscribing
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 1166, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pubnubsubhandler.py", line 124, in _subscribe
    if len(self_pubnubs) == 0:
NameError: name 'self_pubnubs' is not defined

**Comment by joelmoses** [comment]
Same for line 106.

**Comment by w1ll1am23** [comment]
@joelmoses sorry I just saw this. Github notifications are terrible. I believe this is fixed.

**Comment by joelmoses** [comment]
Indeed it is! And I agree about the notifications...

Apologies, I should have gone in and closed this out when I saw it fixed in Main. :)
